<?php
$query = substr($_SERVER["REQUEST_URI"],1);
if (strpos($query,"?")) {
    $tmp = strstr($query,"lang",true);
    if (strlen($tmp) > 0) {
        $query = $tmp;
    } else {
        $query .= "&amp;";    
    }
} else {
    $tmp = strstr($query,"lang",true);
    if (strlen($tmp) > 0) {
        $query = $tmp;
    } else {
        $query .= "?";    
    }
    
}

?>
<!doctype html>
<html>
    <head>
        <title>
            <?=$lang[$langName]["titleAuto"];?>
        </title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" href="css/bootstrap.css">
        <link rel="stylesheet" href="css/style.css">
        <script type="text/javascript" src="js/jquery.js"></script>
        <script type="text/javascript" src="js/bootstrap.js"></script>
        <script type="text/javascript" src="js/ajaxWork.js"></script>
      
    </head>
    <body>
        <header>
                <nav class="navbar ">
                <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                      <a class="navbar-brand" href="index.php"><?=$lang[$langName]["home"];?></a>
                  </div>
              
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="?view=users"><?=$lang[$langName]["users"];?></a></li>
                      <li ><a href="?view=invites"><?=$lang[$langName]["invites"];?></a></li>
                      <li ><a href="#"></a></li>
                        
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                      <li><a href="<?=$query?>lang=<?=($langName == "en") ? "ru": "en";?>" > <?=($langName == "en") ? "ru": "англ";?></a></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <?=$lang[$langName]["profile"];?><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            
                           <?php if (isset($_SESSION['user'])) { ?>
                            <li ><a href="?logout=1"><?=$lang[$langName]["logout"];?></a></li>
                           <?php } else { ?>
                            <li ><a href="index.php"><?=$lang[$langName]["signIn"];?></a></li>
                           <?php }?>
                        </ul>
                      </li>
                    </ul>
                  </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
              </nav>
    
        </header>